[2025-03-05T02:06:33.132+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T02:06:33.175+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_stock_data.load_to_snowflake manual__2025-03-05T02:06:11.570538+00:00 [queued]>
[2025-03-05T02:06:33.196+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_stock_data.load_to_snowflake manual__2025-03-05T02:06:11.570538+00:00 [queued]>
[2025-03-05T02:06:33.200+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-05T02:06:33.222+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_to_snowflake> on 2025-03-05 02:06:11.570538+00:00
[2025-03-05T02:06:33.240+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=470) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T02:06:33.244+0000] {standard_task_runner.py:72} INFO - Started process 479 to run task
[2025-03-05T02:06:33.240+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_stock_data', 'load_to_snowflake', 'manual__2025-03-05T02:06:11.570538+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/extract_stock_data.py', '--cfg-path', '/tmp/tmpf_nmbq52']
[2025-03-05T02:06:33.246+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask load_to_snowflake
[2025-03-05T02:06:33.701+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_stock_data.load_to_snowflake manual__2025-03-05T02:06:11.570538+00:00 [running]> on host 53b5cd688e7b
[2025-03-05T02:06:33.978+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_stock_data' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T02:06:11.570538+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T02:06:11.570538+00:00'
[2025-03-05T02:06:33.983+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T02:06:34.010+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-05T02:06:34.015+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-05T02:06:34.031+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T02:06:34.033+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T02:06:36.694+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T02:06:39.452+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T02:06:39.743+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T02:06:41.526+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T02:06:41.535+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T02:06:41.566+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T02:06:41.569+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_stock_data, task_id=load_to_snowflake, run_id=manual__2025-03-05T02:06:11.570538+00:00, execution_date=20250305T020611, start_date=20250305T020633, end_date=20250305T020641
[2025-03-05T02:06:41.628+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T02:06:41.654+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T02:06:41.656+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
