[2025-03-05T23:41:41.763+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T23:41:41.768+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecast_stock_prices.store_forecast_in_snowflake manual__2025-03-05T23:41:37.491429+00:00 [queued]>
[2025-03-05T23:41:41.770+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecast_stock_prices.store_forecast_in_snowflake manual__2025-03-05T23:41:37.491429+00:00 [queued]>
[2025-03-05T23:41:41.771+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-05T23:41:41.774+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): store_forecast_in_snowflake> on 2025-03-05 23:41:37.491429+00:00
[2025-03-05T23:41:41.779+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=346) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T23:41:41.780+0000] {standard_task_runner.py:72} INFO - Started process 356 to run task
[2025-03-05T23:41:41.779+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecast_stock_prices', 'store_forecast_in_snowflake', 'manual__2025-03-05T23:41:37.491429+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/forecast_stock_prices.py', '--cfg-path', '/tmp/tmppg5yjhpk']
[2025-03-05T23:41:41.780+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask store_forecast_in_snowflake
[2025-03-05T23:41:41.797+0000] {task_command.py:467} INFO - Running <TaskInstance: forecast_stock_prices.store_forecast_in_snowflake manual__2025-03-05T23:41:37.491429+00:00 [running]> on host e79e9b291484
[2025-03-05T23:41:41.828+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecast_stock_prices' AIRFLOW_CTX_TASK_ID='store_forecast_in_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T23:41:37.491429+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T23:41:37.491429+00:00'
[2025-03-05T23:41:41.829+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T23:41:41.834+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-05T23:41:41.834+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-03-05T23:41:41.835+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T23:41:41.835+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T23:41:42.688+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:41:43.990+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:41:43.991+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T23:41:43.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T23:41:43.995+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forecast_stock_prices, task_id=store_forecast_in_snowflake, run_id=manual__2025-03-05T23:41:37.491429+00:00, execution_date=20250305T234137, start_date=20250305T234141, end_date=20250305T234143
[2025-03-05T23:41:44.021+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T23:41:44.029+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T23:41:44.030+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
